const jsSha = require('jssha');

// function to generate a hash for password
function getHash(input) {
  // environment variable to use as a secret word for hashing userId cookie
  // environment variable is currently stored in ~/.bashrc (see RA module 3.6.4)
  const myEnvVar = process.env.MY_ENV_VAR;

  // create new SHA object
  // eslint-disable-next-line new-cap
  const shaObj = new jsSha('SHA-512', 'TEXT', { encoding: 'UTF8' });

  // create an unhashed cookie string based on user ID and myEnVar
  const unhashedString = `${input}-${myEnvVar}`;

  // generate a hashed cookie string using SHA object
  shaObj.update(unhashedString);

  return shaObj.getHash('HEX');
}

// array of objects containing users data
const usersList = [
  {
    name: 'Alvin',
    email: 'alvin@gmail.com',
    password: getHash('alvin'),
    bank_name: 'POSB',
    bank_account_number: '12345678910',
    address: 'Nicoll highway blk700A #09-891',
    country: 'Singapore',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Ben',
    email: 'ben@gmail.com',
    password: getHash('ben'),
    bank_name: 'POSB',
    bank_account_number: '12345678910',
    address: 'Espen highway blk100A #09-891',
    country: 'Singapore',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Kai',
    email: 'kai@gmail.com',
    password: getHash('kai'),
    bank_name: 'OCBC',
    bank_account_number: '12345678910',
    address: '777 Brockton Avenue, Abington MA 2351',
    country: 'United States of America',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Akira',
    email: 'akira@gmail.com',
    password: getHash('akira'),
    bank_name: 'OCBC',
    bank_account_number: '12345678910',
    address: '30 Memorial Drive, Avon MA 2322',
    country: 'United States of America',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Jit Corn',
    email: 'jitcorn@gmail.com',
    password: getHash('jitcorn'),
    bank_name: 'OCBC',
    bank_account_number: '12345678910',
    address: '10, Eoulmadang-ro 2-gil, Mapo-gu, Seoul',
    country: 'Korea, Republic of',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Kenrick',
    email: 'kenrick@gmail.com',
    password: getHash('kenrick'),
    bank_name: 'OCBC',
    bank_account_number: '12345678910',
    address: '20, Eoulmadang-ro 2-gil, Mapo-gu, Seoul',
    country: 'Korea, Republic of',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Jeremy',
    email: 'jeremy@gmail.com',
    password: getHash('jeremy'),
    bank_name: 'OCBC',
    bank_account_number: '12345678910',
    address: 'Higashi Ward, Sapporo, Hokkaido 065-0019',
    country: 'Japan',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Veena',
    email: 'veena@gmail.com',
    password: getHash('veena'),
    bank_name: 'OCBC',
    bank_account_number: '12345678910',
    address: 'Veerapathiran Kovil, Kamakkapalayam, Tamil Nadu 636101, India',
    country: 'India',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: 'Demo User 1',
    email: 'demo1@gmail.com',
    password: getHash('demo-user1'),
    bank_name: 'POSB',
    bank_account_number: '12345678910',
    address: 'Tenah Merah blk700A #09-891',
    country: 'Singapore',
    photo: '/images/profile-photos/anonymous-person.jpg',
    created_at: new Date(),
    updated_at: new Date(),
  },
];

// array of objects containing requests data
const requestsList = [
  {
    category: 'Food & Drinks',
    country: 'Singapore',
    helper_id: null,
    requester_id: 3,
    product_name: 'Bak Kwa',
    description: '1 packet of 500g Bee Cheng Hiang Bak Kwa. Contact me at 89760000.',
    price: '50',
    reference_link: 'https://www.beechenghiang.com.sg/sliced-pork-480g.html',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: '777 Brockton Avenue, Abington MA 2351',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Men Fashion',
    country: 'Singapore',
    helper_id: null,
    requester_id: 4,
    product_name: 'uniqlo shirt',
    description: '1 x Medium uniqlo shirt. Contact me at 89760001.',
    price: '30',
    reference_link: 'https://www.uniqlo.com/sg/store/men-the-game-by-street-fighter-graphic-t-shirt-4193600005.html',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: '30 Memorial Drive, Avon MA 2322',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Games',
    country: 'Singapore',
    helper_id: null,
    requester_id: 5,
    product_name: 'Singaporean Dream',
    description: '1 set of Singaporean Dream cards. Contact me at 89760002.',
    price: '50',
    reference_link: 'https://www.amazon.sg/The-Singaporean-Dream-Base-Set/dp/B081S8NTCC',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: '10, Eoulmadang-ro 2-gil, Mapo-gu, Seoul',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Gadgets',
    country: 'Singapore',
    helper_id: null,
    requester_id: 6,
    product_name: 'prism monitor',
    description: '1 W270 pro prism monitor. Contact me at 89760003.',
    price: '250',
    reference_link: 'https://prismplus.sg/collections/gaming-monitors',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: '20, Eoulmadang-ro 2-gil, Mapo-gu, Seoul',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Sports',
    country: 'Singapore',
    helper_id: null,
    requester_id: 7,
    product_name: 'skateboard',
    description: 'Zero Skateboards Single Skull Black / White Complete Skateboard - 8" x 32". Contact me at 89760004.',
    price: '450',
    reference_link: 'https://www.desertcart.sg/products/55671368-zero-skateboards-single-skull-black-white-complete-skateboard-8-x-32',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: 'Higashi Ward, Sapporo, Hokkaido 065-0019',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Ladies Fashion',
    country: 'Singapore',
    helper_id: null,
    requester_id: 8,
    product_name: 'green dress',
    description: '1 x love bonito dress. Contact me at 89760005.',
    price: '50',
    reference_link: 'https://www.carousell.sg/p/love-bonito-lovebonito-lb-green-dress-141766431/',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: 'Veerapathiran Kovil, Kamakkapalayam, Tamil Nadu 636101, India',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Food & Drinks',
    country: 'Singapore',
    helper_id: null,
    requester_id: 3,
    product_name: 'Seaweed',
    description: '1 packet of seaweed. Contact me at 89760000.',
    price: '20',
    reference_link: 'https://ezbuy.sg/product/475122044.html?keywords=seaweed&baseGpid=475122044&pl=1&ezspm=1.20000000.22.0.0',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: '777 Brockton Avenue, Abington MA 2351',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Collectibles',
    country: 'Singapore',
    helper_id: null,
    requester_id: 4,
    product_name: 'Dolphin mug',
    description: '1 dolpin mug. Contact me at 89760001.',
    price: '50',
    reference_link: 'https://www.lazada.sg/products/dolphin-collection-porcelain-mug-with-cover-coffee-design-i303060070-s536344452.html?spm=a2o42.lazmart_search.list.1.6fb97ec7n2BhNj&search=1',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: '30 Memorial Drive, Avon MA 2322',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Collectibles',
    country: 'Singapore',
    helper_id: null,
    requester_id: 5,
    product_name: 'Gift tags',
    description: '1 packet. Contact me at 89760002.',
    price: '10',
    reference_link: 'https://www.lazada.sg/products/artwrap-coloured-gift-tags-i304170726-s538362875.html?spm=a2o42.lazmart_search.list.2.3b2e8d06nPo6tZ&search=1',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: '10, Eoulmadang-ro 2-gil, Mapo-gu, Seoul',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Food & Drinks',
    country: 'Singapore',
    helper_id: null,
    requester_id: 6,
    product_name: 'milo powder',
    description: '1 packet. Contact me at 89760003.',
    price: '20',
    reference_link: 'https://www.lazada.sg/products/milo-active-go-regular-powder-refill-pack-i301090782-s527090731.html?spm=a2o42.lazmart_search.list.1.6bae1e26NoPu9M&search=1',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: '20, Eoulmadang-ro 2-gil, Mapo-gu, Seoul',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Gadgets',
    country: 'United States of America',
    helper_id: null,
    requester_id: 9,
    product_name: 'Iphone case',
    description: '1 case. Contact me at 89760004.',
    price: '20',
    reference_link: 'https://www.lazada.sg/products/artwrap-party-favors-pirate-silver-earrings-i304034111-s538136757.html?spm=a2o42.lazmart_search.list.1.52093bb5eZo0Mz&search=1',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: 'Tenah Merah blk700A #09-891',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Gadgets',
    country: 'Japan',
    helper_id: null,
    requester_id: 9,
    product_name: 'Robot dog',
    description: '1 robot dog. Contact me at 89760004.',
    price: '20',
    reference_link: 'https://www.amazon.co.jp/-/en/Programming-Electronic-Japanese-Instruction-Guaranteed/dp/B089B7TFHJ',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'requested',
    shipping_address: 'Tenah Merah blk700A #09-891',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    category: 'Food & Drinks',
    country: 'Japan',
    helper_id: null,
    requester_id: 9,
    product_name: 'toms and toms almonds',
    description: '3 garlic butter packets. Contact me at 89760004.',
    price: '80',
    reference_link: 'https://beautyboxkorea.com/product/gilim-toms-farm-garlic-bread-almond-210g/42836/',
    payment_filename: '/images/payments/wire-transfer.jpg',
    status: 'accepted',
    shipping_address: 'Tenah Merah blk700A #09-891',
    created_at: new Date(),
    updated_at: new Date(),
  },

];

// export the seed data as a module
module.exports = {
  usersList,
  requestsList,
};
